import { FC, useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { INextPageWithLayout } from "@/types/INextPageWithLayout";
import Layout from "@/components/templates/Layout/Layout";
import Header from "@/components/organisms/Header/Header";
import Footer from "@/components/organisms/Footer/Footer";
import { GetStaticProps, GetStaticPropsResult } from "next";
import { ICar } from "@/types/ICar";
import carsService from "@/services/carsService";
import { useDispatch } from "react-redux";
import { setCars } from "@/store/actions/setCars";
import { CarActionType } from "@/types/CarActionTypes";
import { Dispatch } from "redux";
import { useTypedSelector } from "@/store/hooks";
import Title from "@/components/atoms/Title/Title";
import CarCardList from "@/components/organisms/CarCardList/CarCardList";
import { Stack } from "react-bootstrap";
import HomePageButtons from "@/components/organisms/HomePageButtons/HomePageButtons";

interface Props {
  cars: ICar[];
}

const HomePage: INextPageWithLayout<Props> = ({ cars }) => {

  const dispatch: Dispatch<CarActionType> = useDispatch();

  useEffect(() => {
    dispatch(setCars(cars));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack gap={2}>
        <Title style={{ textAlign: "center" }}>Home page</Title>
        <HomePageButtons />
        <CarCardList />
      </Stack>
    </>
  )
};

HomePage.getLayout = (page) => {
  return (
    <Layout
      renderHeader={() => <Header />}
      renderFooter={() => <Footer />}
    >
      {page}
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {

  const cars = await carsService.getCars();

  return {
    props: {
      cars: cars || []
    }
  }
}

export default HomePage;
